Update yml file

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,7 +45,15 @@ jobs:
           # Get Chrome version
           CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
           MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
-          LATEST_DRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION) || { echo "Failed to retrieve ChromeDriver version"; exit 1; }
+          
+          # Attempt to fetch ChromeDriver for the Chrome version
+          LATEST_DRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION) || { echo "Failed to retrieve ChromeDriver version for major version $MAJOR_VERSION"; exit 1; }
+          
+          # If failed, fall back to latest ChromeDriver
+          if [ -z "$LATEST_DRIVER" ]; then
+          echo "Fetching latest ChromeDriver version"
+          LATEST_DRIVER=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE) || { echo "Failed to retrieve the latest ChromeDriver version"; exit 1; }
+          fi
           
           # Download and set up ChromeDriver
           wget https://chromedriver.storage.googleapis.com/$LATEST_DRIVER/chromedriver_linux64.zip || { echo "Failed to download ChromeDriver"; exit 1; }
